// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA7e3dd37DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAttachmentsDto(in *jlexer.Lexer, out *Header) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "note_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.NoteID).UnmarshalText(data))
			}
		case "minio_key":
			out.MinioKey = string(in.String())
		case "header_url":
			out.HeaderURL = string(in.String())
		case "url_expires_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.URLExpiresAt).UnmarshalJSON(data))
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA7e3dd37EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAttachmentsDto(out *jwriter.Writer, in Header) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"note_id\":"
		out.RawString(prefix)
		out.RawText((in.NoteID).MarshalText())
	}
	{
		const prefix string = ",\"minio_key\":"
		out.RawString(prefix)
		out.String(string(in.MinioKey))
	}
	{
		const prefix string = ",\"header_url\":"
		out.RawString(prefix)
		out.String(string(in.HeaderURL))
	}
	{
		const prefix string = ",\"url_expires_at\":"
		out.RawString(prefix)
		out.Raw((in.URLExpiresAt).MarshalJSON())
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Header) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA7e3dd37EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAttachmentsDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Header) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA7e3dd37EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAttachmentsDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Header) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA7e3dd37DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAttachmentsDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Header) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA7e3dd37DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAttachmentsDto(l, v)
}
