run:
  timeout: 10m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default: false
  new: false
