// Code generated by MockGen. DO NOT EDIT.
// Source: notes.go
//
// Generated by this command:
//
//	mockgen -source=notes.go -destination=mocks/mock_grpcclient_notes.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gen "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/proto/notes/grpc/gen"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNotesServiceClient is a mock of NotesServiceClient interface.
type MockNotesServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotesServiceClientMockRecorder
	isgomock struct{}
}

// MockNotesServiceClientMockRecorder is the mock recorder for MockNotesServiceClient.
type MockNotesServiceClientMockRecorder struct {
	mock *MockNotesServiceClient
}

// NewMockNotesServiceClient creates a new mock instance.
func NewMockNotesServiceClient(ctrl *gomock.Controller) *MockNotesServiceClient {
	mock := &MockNotesServiceClient{ctrl: ctrl}
	mock.recorder = &MockNotesServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotesServiceClient) EXPECT() *MockNotesServiceClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockNotesServiceClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockNotesServiceClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNotesServiceClient)(nil).Close))
}

// CreateBlock mocks base method.
func (m *MockNotesServiceClient) CreateBlock(ctx context.Context, userID uuid.UUID, block *gen.BlockResponse) (*gen.BlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlock", ctx, userID, block)
	ret0, _ := ret[0].(*gen.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlock indicates an expected call of CreateBlock.
func (mr *MockNotesServiceClientMockRecorder) CreateBlock(ctx, userID, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlock", reflect.TypeOf((*MockNotesServiceClient)(nil).CreateBlock), ctx, userID, block)
}

// DeleteBlock mocks base method.
func (m *MockNotesServiceClient) DeleteBlock(ctx context.Context, blockID, noteID, userID uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockNotesServiceClientMockRecorder) DeleteBlock(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockNotesServiceClient)(nil).DeleteBlock), ctx, blockID, noteID, userID)
}

// GetBlock mocks base method.
func (m *MockNotesServiceClient) GetBlock(ctx context.Context, blockID, noteID, userID uuid.UUID) (*gen.BlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(*gen.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockNotesServiceClientMockRecorder) GetBlock(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockNotesServiceClient)(nil).GetBlock), ctx, blockID, noteID, userID)
}

// GetBlocks mocks base method.
func (m *MockNotesServiceClient) GetBlocks(ctx context.Context, noteID, userID uuid.UUID) ([]*gen.BlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocks", ctx, noteID, userID)
	ret0, _ := ret[0].([]*gen.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockNotesServiceClientMockRecorder) GetBlocks(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocks", reflect.TypeOf((*MockNotesServiceClient)(nil).GetBlocks), ctx, noteID, userID)
}

// GetNote mocks base method.
func (m *MockNotesServiceClient) GetNote(ctx context.Context, noteID, userID uuid.UUID) (*gen.NoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, noteID, userID)
	ret0, _ := ret[0].(*gen.NoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockNotesServiceClientMockRecorder) GetNote(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockNotesServiceClient)(nil).GetNote), ctx, noteID, userID)
}

// ShiftBlockPositions mocks base method.
func (m *MockNotesServiceClient) ShiftBlockPositions(ctx context.Context, noteID uuid.UUID, fromPosition, direction int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShiftBlockPositions", ctx, noteID, fromPosition, direction)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShiftBlockPositions indicates an expected call of ShiftBlockPositions.
func (mr *MockNotesServiceClientMockRecorder) ShiftBlockPositions(ctx, noteID, fromPosition, direction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShiftBlockPositions", reflect.TypeOf((*MockNotesServiceClient)(nil).ShiftBlockPositions), ctx, noteID, fromPosition, direction)
}
