// Code generated by MockGen. DO NOT EDIT.
// Source: attachments.go
//
// Generated by this command:
//
//	mockgen -source=attachments.go -destination=mocks/mock_handler_attachments.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAttachmentClient is a mock of AttachmentClient interface.
type MockAttachmentClient struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentClientMockRecorder
	isgomock struct{}
}

// MockAttachmentClientMockRecorder is the mock recorder for MockAttachmentClient.
type MockAttachmentClientMockRecorder struct {
	mock *MockAttachmentClient
}

// NewMockAttachmentClient creates a new mock instance.
func NewMockAttachmentClient(ctrl *gomock.Controller) *MockAttachmentClient {
	mock := &MockAttachmentClient{ctrl: ctrl}
	mock.recorder = &MockAttachmentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentClient) EXPECT() *MockAttachmentClientMockRecorder {
	return m.recorder
}

// DeleteAttachment mocks base method.
func (m *MockAttachmentClient) DeleteAttachment(ctx context.Context, noteID, blockID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachment", ctx, noteID, blockID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachment indicates an expected call of DeleteAttachment.
func (mr *MockAttachmentClientMockRecorder) DeleteAttachment(ctx, noteID, blockID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachment", reflect.TypeOf((*MockAttachmentClient)(nil).DeleteAttachment), ctx, noteID, blockID, userID)
}

// GetAttachment mocks base method.
func (m *MockAttachmentClient) GetAttachment(ctx context.Context, noteID, blockID, userID uuid.UUID) (*models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachment", ctx, noteID, blockID, userID)
	ret0, _ := ret[0].(*models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachment indicates an expected call of GetAttachment.
func (mr *MockAttachmentClientMockRecorder) GetAttachment(ctx, noteID, blockID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachment", reflect.TypeOf((*MockAttachmentClient)(nil).GetAttachment), ctx, noteID, blockID, userID)
}

// UploadAttachment mocks base method.
func (m *MockAttachmentClient) UploadAttachment(ctx context.Context, noteID, blockID, userID uuid.UUID, fileReader io.Reader, fileName string, fileSize int64, mimeType string) (*models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAttachment", ctx, noteID, blockID, userID, fileReader, fileName, fileSize, mimeType)
	ret0, _ := ret[0].(*models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAttachment indicates an expected call of UploadAttachment.
func (mr *MockAttachmentClientMockRecorder) UploadAttachment(ctx, noteID, blockID, userID, fileReader, fileName, fileSize, mimeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAttachment", reflect.TypeOf((*MockAttachmentClient)(nil).UploadAttachment), ctx, noteID, blockID, userID, fileReader, fileName, fileSize, mimeType)
}
