// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson97d7cd47DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalProfilesDto(in *jlexer.Lexer, out *Avatar) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "ProfileID":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ProfileID).UnmarshalText(data))
			}
		case "MinioKey":
			out.MinioKey = string(in.String())
		case "AvatarURL":
			out.AvatarURL = string(in.String())
		case "URLExpiresAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.URLExpiresAt).UnmarshalJSON(data))
			}
		case "CreatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "UpdatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson97d7cd47EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalProfilesDto(out *jwriter.Writer, in Avatar) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"ProfileID\":"
		out.RawString(prefix)
		out.RawText((in.ProfileID).MarshalText())
	}
	{
		const prefix string = ",\"MinioKey\":"
		out.RawString(prefix)
		out.String(string(in.MinioKey))
	}
	{
		const prefix string = ",\"AvatarURL\":"
		out.RawString(prefix)
		out.String(string(in.AvatarURL))
	}
	{
		const prefix string = ",\"URLExpiresAt\":"
		out.RawString(prefix)
		out.Raw((in.URLExpiresAt).MarshalJSON())
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Avatar) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson97d7cd47EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalProfilesDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Avatar) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson97d7cd47EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalProfilesDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Avatar) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson97d7cd47DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalProfilesDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Avatar) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson97d7cd47DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalProfilesDto(l, v)
}
