// Code generated by MockGen. DO NOT EDIT.
// Source: notes.go
//
// Generated by this command:
//
//	mockgen -source=notes.go -destination=mocks/mock_handler_notes.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteUsecase is a mock of NoteUsecase interface.
type MockNoteUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockNoteUsecaseMockRecorder
	isgomock struct{}
}

// MockNoteUsecaseMockRecorder is the mock recorder for MockNoteUsecase.
type MockNoteUsecaseMockRecorder struct {
	mock *MockNoteUsecase
}

// NewMockNoteUsecase creates a new mock instance.
func NewMockNoteUsecase(ctrl *gomock.Controller) *MockNoteUsecase {
	mock := &MockNoteUsecase{ctrl: ctrl}
	mock.recorder = &MockNoteUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteUsecase) EXPECT() *MockNoteUsecaseMockRecorder {
	return m.recorder
}

// CreateBlock mocks base method.
func (m *MockNoteUsecase) CreateBlock(ctx context.Context, noteID, userID uuid.UUID, block models.Block) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlock", ctx, noteID, userID, block)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlock indicates an expected call of CreateBlock.
func (mr *MockNoteUsecaseMockRecorder) CreateBlock(ctx, noteID, userID, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlock", reflect.TypeOf((*MockNoteUsecase)(nil).CreateBlock), ctx, noteID, userID, block)
}

// CreateNote mocks base method.
func (m *MockNoteUsecase) CreateNote(ctx context.Context, note models.Note) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, note)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteUsecaseMockRecorder) CreateNote(ctx, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteUsecase)(nil).CreateNote), ctx, note)
}

// DeleteBlock mocks base method.
func (m *MockNoteUsecase) DeleteBlock(ctx context.Context, blockID, noteID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockNoteUsecaseMockRecorder) DeleteBlock(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockNoteUsecase)(nil).DeleteBlock), ctx, blockID, noteID, userID)
}

// DeleteNote mocks base method.
func (m *MockNoteUsecase) DeleteNote(ctx context.Context, noteID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, noteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteUsecaseMockRecorder) DeleteNote(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNoteUsecase)(nil).DeleteNote), ctx, noteID, userID)
}

// GetBlock mocks base method.
func (m *MockNoteUsecase) GetBlock(ctx context.Context, blockID, noteID, userID uuid.UUID) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockNoteUsecaseMockRecorder) GetBlock(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockNoteUsecase)(nil).GetBlock), ctx, blockID, noteID, userID)
}

// GetBlockFormatting mocks base method.
func (m *MockNoteUsecase) GetBlockFormatting(ctx context.Context, blockID, noteID, userID uuid.UUID) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockFormatting", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockFormatting indicates an expected call of GetBlockFormatting.
func (mr *MockNoteUsecaseMockRecorder) GetBlockFormatting(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockFormatting", reflect.TypeOf((*MockNoteUsecase)(nil).GetBlockFormatting), ctx, blockID, noteID, userID)
}

// GetBlocks mocks base method.
func (m *MockNoteUsecase) GetBlocks(ctx context.Context, noteID uuid.UUID) ([]models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocks", ctx, noteID)
	ret0, _ := ret[0].([]models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockNoteUsecaseMockRecorder) GetBlocks(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocks", reflect.TypeOf((*MockNoteUsecase)(nil).GetBlocks), ctx, noteID)
}

// GetBlocksWithFormatting mocks base method.
func (m *MockNoteUsecase) GetBlocksWithFormatting(ctx context.Context, noteID uuid.UUID) ([]models.Block, map[string]models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksWithFormatting", ctx, noteID)
	ret0, _ := ret[0].([]models.Block)
	ret1, _ := ret[1].(map[string]models.BlockFormatting)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBlocksWithFormatting indicates an expected call of GetBlocksWithFormatting.
func (mr *MockNoteUsecaseMockRecorder) GetBlocksWithFormatting(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksWithFormatting", reflect.TypeOf((*MockNoteUsecase)(nil).GetBlocksWithFormatting), ctx, noteID)
}

// GetNote mocks base method.
func (m *MockNoteUsecase) GetNote(ctx context.Context, noteID, userID uuid.UUID) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, noteID, userID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockNoteUsecaseMockRecorder) GetNote(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockNoteUsecase)(nil).GetNote), ctx, noteID, userID)
}

// GetNotes mocks base method.
func (m *MockNoteUsecase) GetNotes(ctx context.Context, userID uuid.UUID) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotes", ctx, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotes indicates an expected call of GetNotes.
func (mr *MockNoteUsecaseMockRecorder) GetNotes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotes", reflect.TypeOf((*MockNoteUsecase)(nil).GetNotes), ctx, userID)
}

// MoveBlock mocks base method.
func (m *MockNoteUsecase) MoveBlock(ctx context.Context, blockID, noteID, userID uuid.UUID, newPosition int) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveBlock", ctx, blockID, noteID, userID, newPosition)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveBlock indicates an expected call of MoveBlock.
func (mr *MockNoteUsecaseMockRecorder) MoveBlock(ctx, blockID, noteID, userID, newPosition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveBlock", reflect.TypeOf((*MockNoteUsecase)(nil).MoveBlock), ctx, blockID, noteID, userID, newPosition)
}

// ResetBlockFormatting mocks base method.
func (m *MockNoteUsecase) ResetBlockFormatting(ctx context.Context, blockID, noteID, userID uuid.UUID) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetBlockFormatting", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetBlockFormatting indicates an expected call of ResetBlockFormatting.
func (mr *MockNoteUsecaseMockRecorder) ResetBlockFormatting(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetBlockFormatting", reflect.TypeOf((*MockNoteUsecase)(nil).ResetBlockFormatting), ctx, blockID, noteID, userID)
}

// UpdateBlockContent mocks base method.
func (m *MockNoteUsecase) UpdateBlockContent(ctx context.Context, blockID, noteID, userID uuid.UUID, content string) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockContent", ctx, blockID, noteID, userID, content)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockContent indicates an expected call of UpdateBlockContent.
func (mr *MockNoteUsecaseMockRecorder) UpdateBlockContent(ctx, blockID, noteID, userID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockContent", reflect.TypeOf((*MockNoteUsecase)(nil).UpdateBlockContent), ctx, blockID, noteID, userID, content)
}

// UpdateBlockFormatting mocks base method.
func (m *MockNoteUsecase) UpdateBlockFormatting(ctx context.Context, blockID, noteID, userID uuid.UUID, formattingRange models.FormattingRange) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockFormatting", ctx, blockID, noteID, userID, formattingRange)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockFormatting indicates an expected call of UpdateBlockFormatting.
func (mr *MockNoteUsecaseMockRecorder) UpdateBlockFormatting(ctx, blockID, noteID, userID, formattingRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockFormatting", reflect.TypeOf((*MockNoteUsecase)(nil).UpdateBlockFormatting), ctx, blockID, noteID, userID, formattingRange)
}

// UpdateNote mocks base method.
func (m *MockNoteUsecase) UpdateNote(ctx context.Context, noteID uuid.UUID, note models.Note, userID uuid.UUID) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, noteID, note, userID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNoteUsecaseMockRecorder) UpdateNote(ctx, noteID, note, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNoteUsecase)(nil).UpdateNote), ctx, noteID, note, userID)
}
