// Code generated by MockGen. DO NOT EDIT.
// Source: notes.go
//
// Generated by this command:
//
//	mockgen -source=notes.go -destination=mocks/mock_handler_notes.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteClient is a mock of NoteClient interface.
type MockNoteClient struct {
	ctrl     *gomock.Controller
	recorder *MockNoteClientMockRecorder
	isgomock struct{}
}

// MockNoteClientMockRecorder is the mock recorder for MockNoteClient.
type MockNoteClientMockRecorder struct {
	mock *MockNoteClient
}

// NewMockNoteClient creates a new mock instance.
func NewMockNoteClient(ctrl *gomock.Controller) *MockNoteClient {
	mock := &MockNoteClient{ctrl: ctrl}
	mock.recorder = &MockNoteClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteClient) EXPECT() *MockNoteClientMockRecorder {
	return m.recorder
}

// CreateBlock mocks base method.
func (m *MockNoteClient) CreateBlock(ctx context.Context, noteID, userID uuid.UUID, blockTypeID, position int, content string) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlock", ctx, noteID, userID, blockTypeID, position, content)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlock indicates an expected call of CreateBlock.
func (mr *MockNoteClientMockRecorder) CreateBlock(ctx, noteID, userID, blockTypeID, position, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlock", reflect.TypeOf((*MockNoteClient)(nil).CreateBlock), ctx, noteID, userID, blockTypeID, position, content)
}

// CreateNote mocks base method.
func (m *MockNoteClient) CreateNote(ctx context.Context, userID uuid.UUID, title string, parentID *uuid.UUID) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, userID, title, parentID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteClientMockRecorder) CreateNote(ctx, userID, title, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteClient)(nil).CreateNote), ctx, userID, title, parentID)
}

// CreateSubnote mocks base method.
func (m *MockNoteClient) CreateSubnote(ctx context.Context, parentNoteID, userID uuid.UUID, title string) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubnote", ctx, parentNoteID, userID, title)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubnote indicates an expected call of CreateSubnote.
func (mr *MockNoteClientMockRecorder) CreateSubnote(ctx, parentNoteID, userID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubnote", reflect.TypeOf((*MockNoteClient)(nil).CreateSubnote), ctx, parentNoteID, userID, title)
}

// DeleteBlock mocks base method.
func (m *MockNoteClient) DeleteBlock(ctx context.Context, blockID, noteID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockNoteClientMockRecorder) DeleteBlock(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockNoteClient)(nil).DeleteBlock), ctx, blockID, noteID, userID)
}

// DeleteNote mocks base method.
func (m *MockNoteClient) DeleteNote(ctx context.Context, noteID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, noteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteClientMockRecorder) DeleteNote(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNoteClient)(nil).DeleteNote), ctx, noteID, userID)
}

// DeleteSubnote mocks base method.
func (m *MockNoteClient) DeleteSubnote(ctx context.Context, noteID, subnoteID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubnote", ctx, noteID, subnoteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubnote indicates an expected call of DeleteSubnote.
func (mr *MockNoteClientMockRecorder) DeleteSubnote(ctx, noteID, subnoteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubnote", reflect.TypeOf((*MockNoteClient)(nil).DeleteSubnote), ctx, noteID, subnoteID, userID)
}

// GetBlock mocks base method.
func (m *MockNoteClient) GetBlock(ctx context.Context, blockID, noteID, userID uuid.UUID) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockNoteClientMockRecorder) GetBlock(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockNoteClient)(nil).GetBlock), ctx, blockID, noteID, userID)
}

// GetBlockFormatting mocks base method.
func (m *MockNoteClient) GetBlockFormatting(ctx context.Context, blockID, noteID, userID uuid.UUID) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockFormatting", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockFormatting indicates an expected call of GetBlockFormatting.
func (mr *MockNoteClientMockRecorder) GetBlockFormatting(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockFormatting", reflect.TypeOf((*MockNoteClient)(nil).GetBlockFormatting), ctx, blockID, noteID, userID)
}

// GetBlocks mocks base method.
func (m *MockNoteClient) GetBlocks(ctx context.Context, noteID uuid.UUID) ([]models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocks", ctx, noteID)
	ret0, _ := ret[0].([]models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockNoteClientMockRecorder) GetBlocks(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocks", reflect.TypeOf((*MockNoteClient)(nil).GetBlocks), ctx, noteID)
}

// GetBlocksWithFormatting mocks base method.
func (m *MockNoteClient) GetBlocksWithFormatting(ctx context.Context, noteID uuid.UUID) ([]models.Block, map[string]models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksWithFormatting", ctx, noteID)
	ret0, _ := ret[0].([]models.Block)
	ret1, _ := ret[1].(map[string]models.BlockFormatting)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBlocksWithFormatting indicates an expected call of GetBlocksWithFormatting.
func (mr *MockNoteClientMockRecorder) GetBlocksWithFormatting(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksWithFormatting", reflect.TypeOf((*MockNoteClient)(nil).GetBlocksWithFormatting), ctx, noteID)
}

// GetNote mocks base method.
func (m *MockNoteClient) GetNote(ctx context.Context, noteID, userID uuid.UUID) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, noteID, userID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockNoteClientMockRecorder) GetNote(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockNoteClient)(nil).GetNote), ctx, noteID, userID)
}

// GetNotes mocks base method.
func (m *MockNoteClient) GetNotes(ctx context.Context, userID uuid.UUID) ([]models.Note, map[string][]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotes", ctx, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(map[string][]models.Note)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetNotes indicates an expected call of GetNotes.
func (mr *MockNoteClientMockRecorder) GetNotes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotes", reflect.TypeOf((*MockNoteClient)(nil).GetNotes), ctx, userID)
}

// GetSubnotes mocks base method.
func (m *MockNoteClient) GetSubnotes(ctx context.Context, noteID, userID uuid.UUID) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnotes", ctx, noteID, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnotes indicates an expected call of GetSubnotes.
func (mr *MockNoteClientMockRecorder) GetSubnotes(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnotes", reflect.TypeOf((*MockNoteClient)(nil).GetSubnotes), ctx, noteID, userID)
}

// MoveBlock mocks base method.
func (m *MockNoteClient) MoveBlock(ctx context.Context, blockID, noteID, userID uuid.UUID, newPosition int) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveBlock", ctx, blockID, noteID, userID, newPosition)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveBlock indicates an expected call of MoveBlock.
func (mr *MockNoteClientMockRecorder) MoveBlock(ctx, blockID, noteID, userID, newPosition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveBlock", reflect.TypeOf((*MockNoteClient)(nil).MoveBlock), ctx, blockID, noteID, userID, newPosition)
}

// ResetBlockFormatting mocks base method.
func (m *MockNoteClient) ResetBlockFormatting(ctx context.Context, blockID, noteID, userID uuid.UUID) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetBlockFormatting", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetBlockFormatting indicates an expected call of ResetBlockFormatting.
func (mr *MockNoteClientMockRecorder) ResetBlockFormatting(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetBlockFormatting", reflect.TypeOf((*MockNoteClient)(nil).ResetBlockFormatting), ctx, blockID, noteID, userID)
}

// UpdateBlockContent mocks base method.
func (m *MockNoteClient) UpdateBlockContent(ctx context.Context, blockID, noteID, userID uuid.UUID, content string) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockContent", ctx, blockID, noteID, userID, content)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockContent indicates an expected call of UpdateBlockContent.
func (mr *MockNoteClientMockRecorder) UpdateBlockContent(ctx, blockID, noteID, userID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockContent", reflect.TypeOf((*MockNoteClient)(nil).UpdateBlockContent), ctx, blockID, noteID, userID, content)
}

// UpdateBlockFormatting mocks base method.
func (m *MockNoteClient) UpdateBlockFormatting(ctx context.Context, blockID, noteID, userID uuid.UUID, formattingRange models.FormattingRange) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockFormatting", ctx, blockID, noteID, userID, formattingRange)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockFormatting indicates an expected call of UpdateBlockFormatting.
func (mr *MockNoteClientMockRecorder) UpdateBlockFormatting(ctx, blockID, noteID, userID, formattingRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockFormatting", reflect.TypeOf((*MockNoteClient)(nil).UpdateBlockFormatting), ctx, blockID, noteID, userID, formattingRange)
}

// UpdateNote mocks base method.
func (m *MockNoteClient) UpdateNote(ctx context.Context, noteID, userID uuid.UUID, title string, parentID *uuid.UUID) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, noteID, userID, title, parentID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNoteClientMockRecorder) UpdateNote(ctx, noteID, userID, title, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNoteClient)(nil).UpdateNote), ctx, noteID, userID, title, parentID)
}
