// Code generated by MockGen. DO NOT EDIT.
// Source: profile.go
//
// Generated by this command:
//
//	mockgen -source=profile.go -destination=mocks/mock_repository_profile.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMinIOService is a mock of MinIOService interface.
type MockMinIOService struct {
	ctrl     *gomock.Controller
	recorder *MockMinIOServiceMockRecorder
	isgomock struct{}
}

// MockMinIOServiceMockRecorder is the mock recorder for MockMinIOService.
type MockMinIOServiceMockRecorder struct {
	mock *MockMinIOService
}

// NewMockMinIOService creates a new mock instance.
func NewMockMinIOService(ctrl *gomock.Controller) *MockMinIOService {
	mock := &MockMinIOService{ctrl: ctrl}
	mock.recorder = &MockMinIOServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinIOService) EXPECT() *MockMinIOServiceMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockMinIOService) DeleteFile(ctx context.Context, bucketName, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, bucketName, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockMinIOServiceMockRecorder) DeleteFile(ctx, bucketName, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockMinIOService)(nil).DeleteFile), ctx, bucketName, key)
}

// GeneratePresignedURL mocks base method.
func (m *MockMinIOService) GeneratePresignedURL(ctx context.Context, bucketName, key string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, bucketName, key, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockMinIOServiceMockRecorder) GeneratePresignedURL(ctx, bucketName, key, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockMinIOService)(nil).GeneratePresignedURL), ctx, bucketName, key, expiry)
}

// UploadFile mocks base method.
func (m *MockMinIOService) UploadFile(ctx context.Context, bucketName, key string, reader io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, bucketName, key, reader, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockMinIOServiceMockRecorder) UploadFile(ctx, bucketName, key, reader, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockMinIOService)(nil).UploadFile), ctx, bucketName, key, reader, size, contentType)
}
