// Code generated by MockGen. DO NOT EDIT.
// Source: attachments.go
//
// Generated by this command:
//
//	mockgen -source=attachments.go -destination=mocks/mock_handler_attachments.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAttachmentUsecase is a mock of AttachmentUsecase interface.
type MockAttachmentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentUsecaseMockRecorder
	isgomock struct{}
}

// MockAttachmentUsecaseMockRecorder is the mock recorder for MockAttachmentUsecase.
type MockAttachmentUsecaseMockRecorder struct {
	mock *MockAttachmentUsecase
}

// NewMockAttachmentUsecase creates a new mock instance.
func NewMockAttachmentUsecase(ctrl *gomock.Controller) *MockAttachmentUsecase {
	mock := &MockAttachmentUsecase{ctrl: ctrl}
	mock.recorder = &MockAttachmentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentUsecase) EXPECT() *MockAttachmentUsecaseMockRecorder {
	return m.recorder
}

// DeleteAttachment mocks base method.
func (m *MockAttachmentUsecase) DeleteAttachment(ctx context.Context, noteID, blockID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachment", ctx, noteID, blockID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachment indicates an expected call of DeleteAttachment.
func (mr *MockAttachmentUsecaseMockRecorder) DeleteAttachment(ctx, noteID, blockID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachment", reflect.TypeOf((*MockAttachmentUsecase)(nil).DeleteAttachment), ctx, noteID, blockID, userID)
}

// DeleteHeader mocks base method.
func (m *MockAttachmentUsecase) DeleteHeader(ctx context.Context, noteID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHeader", ctx, noteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHeader indicates an expected call of DeleteHeader.
func (mr *MockAttachmentUsecaseMockRecorder) DeleteHeader(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHeader", reflect.TypeOf((*MockAttachmentUsecase)(nil).DeleteHeader), ctx, noteID, userID)
}

// GetAttachment mocks base method.
func (m *MockAttachmentUsecase) GetAttachment(ctx context.Context, noteID, blockID, userID uuid.UUID) (*models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachment", ctx, noteID, blockID, userID)
	ret0, _ := ret[0].(*models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachment indicates an expected call of GetAttachment.
func (mr *MockAttachmentUsecaseMockRecorder) GetAttachment(ctx, noteID, blockID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachment", reflect.TypeOf((*MockAttachmentUsecase)(nil).GetAttachment), ctx, noteID, blockID, userID)
}

// GetHeader mocks base method.
func (m *MockAttachmentUsecase) GetHeader(ctx context.Context, noteID, userID uuid.UUID) (*models.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeader", ctx, noteID, userID)
	ret0, _ := ret[0].(*models.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeader indicates an expected call of GetHeader.
func (mr *MockAttachmentUsecaseMockRecorder) GetHeader(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeader", reflect.TypeOf((*MockAttachmentUsecase)(nil).GetHeader), ctx, noteID, userID)
}

// UploadAttachment mocks base method.
func (m *MockAttachmentUsecase) UploadAttachment(ctx context.Context, noteID, userID uuid.UUID, fileName string, fileSize int64, mimeType string, fileReader io.Reader, hasPosition bool, position int) (*models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAttachment", ctx, noteID, userID, fileName, fileSize, mimeType, fileReader, hasPosition, position)
	ret0, _ := ret[0].(*models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAttachment indicates an expected call of UploadAttachment.
func (mr *MockAttachmentUsecaseMockRecorder) UploadAttachment(ctx, noteID, userID, fileName, fileSize, mimeType, fileReader, hasPosition, position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAttachment", reflect.TypeOf((*MockAttachmentUsecase)(nil).UploadAttachment), ctx, noteID, userID, fileName, fileSize, mimeType, fileReader, hasPosition, position)
}

// UploadHeader mocks base method.
func (m *MockAttachmentUsecase) UploadHeader(ctx context.Context, noteID, userID uuid.UUID, fileName string, fileSize int64, mimeType string, fileReader io.Reader) (*models.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadHeader", ctx, noteID, userID, fileName, fileSize, mimeType, fileReader)
	ret0, _ := ret[0].(*models.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadHeader indicates an expected call of UploadHeader.
func (mr *MockAttachmentUsecaseMockRecorder) UploadHeader(ctx, noteID, userID, fileName, fileSize, mimeType, fileReader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadHeader", reflect.TypeOf((*MockAttachmentUsecase)(nil).UploadHeader), ctx, noteID, userID, fileName, fileSize, mimeType, fileReader)
}
