FROM golang:latest AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /profiles ./cmd/profiles

FROM alpine:latest AS run

COPY --from=build /profiles /profiles

WORKDIR /app
EXPOSE 50053
CMD ["/profiles"]
