// Code generated by MockGen. DO NOT EDIT.
// Source: profiles.go
//
// Generated by this command:
//
//	mockgen -source=profiles.go -destination=mocks/mock_grpcclient_profiles.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gen "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/proto/profiles/grpc/gen"
	gomock "go.uber.org/mock/gomock"
)

// MockProfilesServiceClient is a mock of ProfilesServiceClient interface.
type MockProfilesServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockProfilesServiceClientMockRecorder
	isgomock struct{}
}

// MockProfilesServiceClientMockRecorder is the mock recorder for MockProfilesServiceClient.
type MockProfilesServiceClientMockRecorder struct {
	mock *MockProfilesServiceClient
}

// NewMockProfilesServiceClient creates a new mock instance.
func NewMockProfilesServiceClient(ctrl *gomock.Controller) *MockProfilesServiceClient {
	mock := &MockProfilesServiceClient{ctrl: ctrl}
	mock.recorder = &MockProfilesServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfilesServiceClient) EXPECT() *MockProfilesServiceClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProfilesServiceClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProfilesServiceClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProfilesServiceClient)(nil).Close))
}

// SigninUser mocks base method.
func (m *MockProfilesServiceClient) SigninUser(ctx context.Context, username string) (*gen.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SigninUser", ctx, username)
	ret0, _ := ret[0].(*gen.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SigninUser indicates an expected call of SigninUser.
func (mr *MockProfilesServiceClientMockRecorder) SigninUser(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SigninUser", reflect.TypeOf((*MockProfilesServiceClient)(nil).SigninUser), ctx, username)
}

// SignupUser mocks base method.
func (m *MockProfilesServiceClient) SignupUser(ctx context.Context, username, password string) (*gen.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignupUser", ctx, username, password)
	ret0, _ := ret[0].(*gen.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignupUser indicates an expected call of SignupUser.
func (mr *MockProfilesServiceClientMockRecorder) SignupUser(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignupUser", reflect.TypeOf((*MockProfilesServiceClient)(nil).SignupUser), ctx, username, password)
}
