// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2ff71951DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(in *jlexer.Lexer, out *BlockWithFormatting) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "formatting":
			(out.Formatting).UnmarshalEasyJSON(in)
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "note_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.NoteID).UnmarshalText(data))
			}
		case "block_type_id":
			out.BlockTypeID = int(in.Int())
		case "position":
			out.Position = int(in.Int())
		case "content":
			out.Content = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(out *jwriter.Writer, in BlockWithFormatting) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"formatting\":"
		out.RawString(prefix[1:])
		(in.Formatting).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"note_id\":"
		out.RawString(prefix)
		out.RawText((in.NoteID).MarshalText())
	}
	{
		const prefix string = ",\"block_type_id\":"
		out.RawString(prefix)
		out.Int(int(in.BlockTypeID))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Int(int(in.Position))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BlockWithFormatting) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BlockWithFormatting) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BlockWithFormatting) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BlockWithFormatting) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(l, v)
}
func easyjson2ff71951DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(in *jlexer.Lexer, out *Block) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "note_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.NoteID).UnmarshalText(data))
			}
		case "block_type_id":
			out.BlockTypeID = int(in.Int())
		case "position":
			out.Position = int(in.Int())
		case "content":
			out.Content = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(out *jwriter.Writer, in Block) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"note_id\":"
		out.RawString(prefix)
		out.RawText((in.NoteID).MarshalText())
	}
	{
		const prefix string = ",\"block_type_id\":"
		out.RawString(prefix)
		out.Int(int(in.BlockTypeID))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Int(int(in.Position))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Block) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Block) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Block) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Block) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(l, v)
}
