// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAd96cba2DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(in *jlexer.Lexer, out *UpdateBlockContentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "content":
			out.Content = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAd96cba2EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(out *jwriter.Writer, in UpdateBlockContentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix[1:])
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateBlockContentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAd96cba2EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateBlockContentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAd96cba2EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateBlockContentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAd96cba2DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateBlockContentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAd96cba2DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(l, v)
}
func easyjsonAd96cba2DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(in *jlexer.Lexer, out *MoveBlockRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "new_position":
			out.NewPosition = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAd96cba2EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(out *jwriter.Writer, in MoveBlockRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"new_position\":"
		out.RawString(prefix[1:])
		out.Int(int(in.NewPosition))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MoveBlockRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAd96cba2EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MoveBlockRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAd96cba2EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MoveBlockRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAd96cba2DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MoveBlockRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAd96cba2DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(l, v)
}
func easyjsonAd96cba2DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto2(in *jlexer.Lexer, out *BlockRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "note_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.NoteID).UnmarshalText(data))
			}
		case "block_type_id":
			out.BlockTypeID = int(in.Int())
		case "position":
			out.Position = int(in.Int())
		case "content":
			out.Content = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAd96cba2EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto2(out *jwriter.Writer, in BlockRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"note_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.NoteID).MarshalText())
	}
	{
		const prefix string = ",\"block_type_id\":"
		out.RawString(prefix)
		out.Int(int(in.BlockTypeID))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Int(int(in.Position))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BlockRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAd96cba2EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BlockRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAd96cba2EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BlockRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAd96cba2DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BlockRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAd96cba2DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto2(l, v)
}
