// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson86c7ad75DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(in *jlexer.Lexer, out *FormattingRange) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "start_pos":
			out.StartPos = int(in.Int())
		case "end_pos":
			out.EndPos = int(in.Int())
		case "bold":
			if in.IsNull() {
				in.Skip()
				out.Bold = nil
			} else {
				if out.Bold == nil {
					out.Bold = new(bool)
				}
				*out.Bold = bool(in.Bool())
			}
		case "italic":
			if in.IsNull() {
				in.Skip()
				out.Italic = nil
			} else {
				if out.Italic == nil {
					out.Italic = new(bool)
				}
				*out.Italic = bool(in.Bool())
			}
		case "underline":
			if in.IsNull() {
				in.Skip()
				out.Underline = nil
			} else {
				if out.Underline == nil {
					out.Underline = new(bool)
				}
				*out.Underline = bool(in.Bool())
			}
		case "text_align":
			if in.IsNull() {
				in.Skip()
				out.TextAlign = nil
			} else {
				if out.TextAlign == nil {
					out.TextAlign = new(int)
				}
				*out.TextAlign = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c7ad75EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(out *jwriter.Writer, in FormattingRange) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start_pos\":"
		out.RawString(prefix[1:])
		out.Int(int(in.StartPos))
	}
	{
		const prefix string = ",\"end_pos\":"
		out.RawString(prefix)
		out.Int(int(in.EndPos))
	}
	if in.Bold != nil {
		const prefix string = ",\"bold\":"
		out.RawString(prefix)
		out.Bool(bool(*in.Bold))
	}
	if in.Italic != nil {
		const prefix string = ",\"italic\":"
		out.RawString(prefix)
		out.Bool(bool(*in.Italic))
	}
	if in.Underline != nil {
		const prefix string = ",\"underline\":"
		out.RawString(prefix)
		out.Bool(bool(*in.Underline))
	}
	if in.TextAlign != nil {
		const prefix string = ",\"text_align\":"
		out.RawString(prefix)
		out.Int(int(*in.TextAlign))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FormattingRange) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86c7ad75EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FormattingRange) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86c7ad75EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FormattingRange) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86c7ad75DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FormattingRange) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86c7ad75DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(l, v)
}
func easyjson86c7ad75DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(in *jlexer.Lexer, out *BlockFormatting) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "block_id":
			out.BlockID = string(in.String())
		case "ranges":
			if in.IsNull() {
				in.Skip()
				out.Ranges = nil
			} else {
				in.Delim('[')
				if out.Ranges == nil {
					if !in.IsDelim(']') {
						out.Ranges = make([]FormattingRange, 0, 1)
					} else {
						out.Ranges = []FormattingRange{}
					}
				} else {
					out.Ranges = (out.Ranges)[:0]
				}
				for !in.IsDelim(']') {
					var v1 FormattingRange
					(v1).UnmarshalEasyJSON(in)
					out.Ranges = append(out.Ranges, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson86c7ad75EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(out *jwriter.Writer, in BlockFormatting) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"block_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.BlockID))
	}
	{
		const prefix string = ",\"ranges\":"
		out.RawString(prefix)
		if in.Ranges == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Ranges {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BlockFormatting) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson86c7ad75EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BlockFormatting) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson86c7ad75EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BlockFormatting) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson86c7ad75DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BlockFormatting) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson86c7ad75DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(l, v)
}
