// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5e74150dDecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(in *jlexer.Lexer, out *NoteResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "note":
			(out.Note).UnmarshalEasyJSON(in)
		case "blocks":
			if in.IsNull() {
				in.Skip()
				out.Blocks = nil
			} else {
				in.Delim('[')
				if out.Blocks == nil {
					if !in.IsDelim(']') {
						out.Blocks = make([]BlockWithFormatting, 0, 0)
					} else {
						out.Blocks = []BlockWithFormatting{}
					}
				} else {
					out.Blocks = (out.Blocks)[:0]
				}
				for !in.IsDelim(']') {
					var v1 BlockWithFormatting
					(v1).UnmarshalEasyJSON(in)
					out.Blocks = append(out.Blocks, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5e74150dEncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(out *jwriter.Writer, in NoteResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"note\":"
		out.RawString(prefix[1:])
		(in.Note).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"blocks\":"
		out.RawString(prefix)
		if in.Blocks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Blocks {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NoteResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5e74150dEncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NoteResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5e74150dEncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NoteResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5e74150dDecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NoteResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5e74150dDecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(l, v)
}
