// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	uuid "github.com/google/uuid"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson33127bb1DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(in *jlexer.Lexer, out *NoteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			out.Title = string(in.String())
		case "parent_id":
			if in.IsNull() {
				in.Skip()
				out.ParentID = nil
			} else {
				if out.ParentID == nil {
					out.ParentID = new(uuid.UUID)
				}
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((*out.ParentID).UnmarshalText(data))
				}
			}
		case "is_public":
			out.IsPublic = bool(in.Bool())
		case "is_favorite":
			out.IsFavorite = bool(in.Bool())
		case "icon":
			out.Icon = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson33127bb1EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(out *jwriter.Writer, in NoteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	if in.ParentID != nil {
		const prefix string = ",\"parent_id\":"
		out.RawString(prefix)
		out.RawText((*in.ParentID).MarshalText())
	}
	{
		const prefix string = ",\"is_public\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsPublic))
	}
	{
		const prefix string = ",\"is_favorite\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsFavorite))
	}
	{
		const prefix string = ",\"icon\":"
		out.RawString(prefix)
		out.String(string(in.Icon))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NoteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson33127bb1EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NoteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson33127bb1EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NoteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson33127bb1DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NoteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson33127bb1DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(l, v)
}
