// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	uuid "github.com/google/uuid"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5e0d3bb8DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(in *jlexer.Lexer, out *Subnote) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "note":
			(out.Note).UnmarshalEasyJSON(in)
		case "block_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.BlockID).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5e0d3bb8EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(out *jwriter.Writer, in Subnote) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"note\":"
		out.RawString(prefix[1:])
		(in.Note).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"block_id\":"
		out.RawString(prefix)
		out.RawText((in.BlockID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Subnote) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5e0d3bb8EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Subnote) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5e0d3bb8EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Subnote) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5e0d3bb8DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Subnote) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5e0d3bb8DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto(l, v)
}
func easyjson5e0d3bb8DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(in *jlexer.Lexer, out *Note) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "user_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UserID).UnmarshalText(data))
			}
		case "title":
			out.Title = string(in.String())
		case "parent_id":
			if in.IsNull() {
				in.Skip()
				out.ParentID = nil
			} else {
				if out.ParentID == nil {
					out.ParentID = new(uuid.UUID)
				}
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((*out.ParentID).UnmarshalText(data))
				}
			}
		case "is_public":
			out.IsPublic = bool(in.Bool())
		case "is_favorite":
			out.IsFavorite = bool(in.Bool())
		case "icon":
			out.Icon = string(in.String())
		case "header_url":
			out.HeaderURL = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5e0d3bb8EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(out *jwriter.Writer, in Note) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.RawText((in.UserID).MarshalText())
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	if in.ParentID != nil {
		const prefix string = ",\"parent_id\":"
		out.RawString(prefix)
		out.RawText((*in.ParentID).MarshalText())
	}
	{
		const prefix string = ",\"is_public\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsPublic))
	}
	{
		const prefix string = ",\"is_favorite\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsFavorite))
	}
	{
		const prefix string = ",\"icon\":"
		out.RawString(prefix)
		out.String(string(in.Icon))
	}
	{
		const prefix string = ",\"header_url\":"
		out.RawString(prefix)
		out.String(string(in.HeaderURL))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Note) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5e0d3bb8EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Note) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5e0d3bb8EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Note) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5e0d3bb8DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Note) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5e0d3bb8DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalNotesDto1(l, v)
}
