// Code generated by MockGen. DO NOT EDIT.
// Source: attachments.go
//
// Generated by this command:
//
//	mockgen -source=attachments.go -destination=mocks/mock_usecase_attachments.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAttachmentRepository is a mock of AttachmentRepository interface.
type MockAttachmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentRepositoryMockRecorder
	isgomock struct{}
}

// MockAttachmentRepositoryMockRecorder is the mock recorder for MockAttachmentRepository.
type MockAttachmentRepositoryMockRecorder struct {
	mock *MockAttachmentRepository
}

// NewMockAttachmentRepository creates a new mock instance.
func NewMockAttachmentRepository(ctrl *gomock.Controller) *MockAttachmentRepository {
	mock := &MockAttachmentRepository{ctrl: ctrl}
	mock.recorder = &MockAttachmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentRepository) EXPECT() *MockAttachmentRepositoryMockRecorder {
	return m.recorder
}

// DeleteAttachment mocks base method.
func (m *MockAttachmentRepository) DeleteAttachment(ctx context.Context, blockID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachment", ctx, blockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachment indicates an expected call of DeleteAttachment.
func (mr *MockAttachmentRepositoryMockRecorder) DeleteAttachment(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachment", reflect.TypeOf((*MockAttachmentRepository)(nil).DeleteAttachment), ctx, blockID)
}

// DeleteHeader mocks base method.
func (m *MockAttachmentRepository) DeleteHeader(ctx context.Context, noteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHeader", ctx, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHeader indicates an expected call of DeleteHeader.
func (mr *MockAttachmentRepositoryMockRecorder) DeleteHeader(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHeader", reflect.TypeOf((*MockAttachmentRepository)(nil).DeleteHeader), ctx, noteID)
}

// GetAttachment mocks base method.
func (m *MockAttachmentRepository) GetAttachment(ctx context.Context, blockID uuid.UUID) (*models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachment", ctx, blockID)
	ret0, _ := ret[0].(*models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachment indicates an expected call of GetAttachment.
func (mr *MockAttachmentRepositoryMockRecorder) GetAttachment(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachment", reflect.TypeOf((*MockAttachmentRepository)(nil).GetAttachment), ctx, blockID)
}

// GetHeader mocks base method.
func (m *MockAttachmentRepository) GetHeader(ctx context.Context, noteID uuid.UUID) (*models.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeader", ctx, noteID)
	ret0, _ := ret[0].(*models.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeader indicates an expected call of GetHeader.
func (mr *MockAttachmentRepositoryMockRecorder) GetHeader(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeader", reflect.TypeOf((*MockAttachmentRepository)(nil).GetHeader), ctx, noteID)
}

// UploadAttachment mocks base method.
func (m *MockAttachmentRepository) UploadAttachment(ctx context.Context, blockID uuid.UUID, fileName string, fileSize int64, mimeType string, fileReader io.Reader) (*models.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAttachment", ctx, blockID, fileName, fileSize, mimeType, fileReader)
	ret0, _ := ret[0].(*models.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAttachment indicates an expected call of UploadAttachment.
func (mr *MockAttachmentRepositoryMockRecorder) UploadAttachment(ctx, blockID, fileName, fileSize, mimeType, fileReader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAttachment", reflect.TypeOf((*MockAttachmentRepository)(nil).UploadAttachment), ctx, blockID, fileName, fileSize, mimeType, fileReader)
}

// UploadHeader mocks base method.
func (m *MockAttachmentRepository) UploadHeader(ctx context.Context, noteID uuid.UUID, fileName string, fileSize int64, mimeType string, fileReader io.Reader) (*models.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadHeader", ctx, noteID, fileName, fileSize, mimeType, fileReader)
	ret0, _ := ret[0].(*models.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadHeader indicates an expected call of UploadHeader.
func (mr *MockAttachmentRepositoryMockRecorder) UploadHeader(ctx, noteID, fileName, fileSize, mimeType, fileReader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadHeader", reflect.TypeOf((*MockAttachmentRepository)(nil).UploadHeader), ctx, noteID, fileName, fileSize, mimeType, fileReader)
}
