// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/mock_handler_auth.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	config "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/internal/config"
	models "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthUsecase is a mock of AuthUsecase interface.
type MockAuthUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUsecaseMockRecorder
	isgomock struct{}
}

// MockAuthUsecaseMockRecorder is the mock recorder for MockAuthUsecase.
type MockAuthUsecaseMockRecorder struct {
	mock *MockAuthUsecase
}

// NewMockAuthUsecase creates a new mock instance.
func NewMockAuthUsecase(ctrl *gomock.Controller) *MockAuthUsecase {
	mock := &MockAuthUsecase{ctrl: ctrl}
	mock.recorder = &MockAuthUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUsecase) EXPECT() *MockAuthUsecaseMockRecorder {
	return m.recorder
}

// Logout mocks base method.
func (m *MockAuthUsecase) Logout(ctx context.Context, w http.ResponseWriter, jwtCfg config.JWTConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Logout", ctx, w, jwtCfg)
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthUsecaseMockRecorder) Logout(ctx, w, jwtCfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthUsecase)(nil).Logout), ctx, w, jwtCfg)
}

// SigninUser mocks base method.
func (m *MockAuthUsecase) SigninUser(ctx context.Context, username, password string) (*models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SigninUser", ctx, username, password)
	ret0, _ := ret[0].(*models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SigninUser indicates an expected call of SigninUser.
func (mr *MockAuthUsecaseMockRecorder) SigninUser(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SigninUser", reflect.TypeOf((*MockAuthUsecase)(nil).SigninUser), ctx, username, password)
}

// SignupUser mocks base method.
func (m *MockAuthUsecase) SignupUser(ctx context.Context, username, password string) (*models.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignupUser", ctx, username, password)
	ret0, _ := ret[0].(*models.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignupUser indicates an expected call of SignupUser.
func (mr *MockAuthUsecaseMockRecorder) SignupUser(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignupUser", reflect.TypeOf((*MockAuthUsecase)(nil).SignupUser), ctx, username, password)
}
