// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4f592df5DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAuthDto(in *jlexer.Lexer, out *SignUpUser) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "username":
			out.Username = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f592df5EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAuthDto(out *jwriter.Writer, in SignUpUser) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SignUpUser) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4f592df5EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAuthDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SignUpUser) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4f592df5EncodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAuthDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SignUpUser) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4f592df5DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAuthDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SignUpUser) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4f592df5DecodeGithubComGoParkMailRu20261WHITECROWSOFTInternalAuthDto(l, v)
}
