FROM golang:latest AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /attachments ./cmd/attachments

FROM alpine:latest AS run

COPY --from=build /attachments /attachments

WORKDIR /app
EXPOSE 50051
CMD ["/attachments"]
