// Code generated by MockGen. DO NOT EDIT.
// Source: notes.go
//
// Generated by this command:
//
//	mockgen -source=notes.go -destination=mocks/mock_usecase_notes.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteRepository is a mock of NoteRepository interface.
type MockNoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNoteRepositoryMockRecorder
	isgomock struct{}
}

// MockNoteRepositoryMockRecorder is the mock recorder for MockNoteRepository.
type MockNoteRepositoryMockRecorder struct {
	mock *MockNoteRepository
}

// NewMockNoteRepository creates a new mock instance.
func NewMockNoteRepository(ctrl *gomock.Controller) *MockNoteRepository {
	mock := &MockNoteRepository{ctrl: ctrl}
	mock.recorder = &MockNoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteRepository) EXPECT() *MockNoteRepositoryMockRecorder {
	return m.recorder
}

// CreateBlock mocks base method.
func (m *MockNoteRepository) CreateBlock(ctx context.Context, block models.Block) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlock", ctx, block)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlock indicates an expected call of CreateBlock.
func (mr *MockNoteRepositoryMockRecorder) CreateBlock(ctx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlock", reflect.TypeOf((*MockNoteRepository)(nil).CreateBlock), ctx, block)
}

// CreateNote mocks base method.
func (m *MockNoteRepository) CreateNote(ctx context.Context, note models.Note) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, note)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteRepositoryMockRecorder) CreateNote(ctx, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteRepository)(nil).CreateNote), ctx, note)
}

// DeleteBlock mocks base method.
func (m *MockNoteRepository) DeleteBlock(ctx context.Context, blockID uuid.UUID) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, blockID)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockNoteRepositoryMockRecorder) DeleteBlock(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockNoteRepository)(nil).DeleteBlock), ctx, blockID)
}

// DeleteNote mocks base method.
func (m *MockNoteRepository) DeleteNote(ctx context.Context, noteID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteRepositoryMockRecorder) DeleteNote(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNoteRepository)(nil).DeleteNote), ctx, noteID)
}

// GetBlock mocks base method.
func (m *MockNoteRepository) GetBlock(ctx context.Context, blockID uuid.UUID) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", ctx, blockID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockNoteRepositoryMockRecorder) GetBlock(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockNoteRepository)(nil).GetBlock), ctx, blockID)
}

// GetBlockFormatting mocks base method.
func (m *MockNoteRepository) GetBlockFormatting(ctx context.Context, blockID uuid.UUID) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockFormatting", ctx, blockID)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockFormatting indicates an expected call of GetBlockFormatting.
func (mr *MockNoteRepositoryMockRecorder) GetBlockFormatting(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockFormatting", reflect.TypeOf((*MockNoteRepository)(nil).GetBlockFormatting), ctx, blockID)
}

// GetBlockType mocks base method.
func (m *MockNoteRepository) GetBlockType(ctx context.Context, blockTypeID int) (*models.BlockType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockType", ctx, blockTypeID)
	ret0, _ := ret[0].(*models.BlockType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockType indicates an expected call of GetBlockType.
func (mr *MockNoteRepositoryMockRecorder) GetBlockType(ctx, blockTypeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockType", reflect.TypeOf((*MockNoteRepository)(nil).GetBlockType), ctx, blockTypeID)
}

// GetBlocks mocks base method.
func (m *MockNoteRepository) GetBlocks(ctx context.Context, noteID uuid.UUID) ([]models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocks", ctx, noteID)
	ret0, _ := ret[0].([]models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockNoteRepositoryMockRecorder) GetBlocks(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocks", reflect.TypeOf((*MockNoteRepository)(nil).GetBlocks), ctx, noteID)
}

// GetBlocksFormatting mocks base method.
func (m *MockNoteRepository) GetBlocksFormatting(ctx context.Context, blockIDs []uuid.UUID) (map[string]models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksFormatting", ctx, blockIDs)
	ret0, _ := ret[0].(map[string]models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksFormatting indicates an expected call of GetBlocksFormatting.
func (mr *MockNoteRepositoryMockRecorder) GetBlocksFormatting(ctx, blockIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksFormatting", reflect.TypeOf((*MockNoteRepository)(nil).GetBlocksFormatting), ctx, blockIDs)
}

// GetNote mocks base method.
func (m *MockNoteRepository) GetNote(ctx context.Context, noteID uuid.UUID) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, noteID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockNoteRepositoryMockRecorder) GetNote(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockNoteRepository)(nil).GetNote), ctx, noteID)
}

// GetNotes mocks base method.
func (m *MockNoteRepository) GetNotes(ctx context.Context, userID uuid.UUID) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotes", ctx, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotes indicates an expected call of GetNotes.
func (mr *MockNoteRepositoryMockRecorder) GetNotes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotes", reflect.TypeOf((*MockNoteRepository)(nil).GetNotes), ctx, userID)
}

// GetSubnotes mocks base method.
func (m *MockNoteRepository) GetSubnotes(ctx context.Context, noteID uuid.UUID) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnotes", ctx, noteID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnotes indicates an expected call of GetSubnotes.
func (mr *MockNoteRepositoryMockRecorder) GetSubnotes(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnotes", reflect.TypeOf((*MockNoteRepository)(nil).GetSubnotes), ctx, noteID)
}

// MoveBlock mocks base method.
func (m *MockNoteRepository) MoveBlock(ctx context.Context, noteID, blockID uuid.UUID, oldPosition, newPosition int, updatedAt time.Time) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveBlock", ctx, noteID, blockID, oldPosition, newPosition, updatedAt)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveBlock indicates an expected call of MoveBlock.
func (mr *MockNoteRepositoryMockRecorder) MoveBlock(ctx, noteID, blockID, oldPosition, newPosition, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveBlock", reflect.TypeOf((*MockNoteRepository)(nil).MoveBlock), ctx, noteID, blockID, oldPosition, newPosition, updatedAt)
}

// ResetBlockFormatting mocks base method.
func (m *MockNoteRepository) ResetBlockFormatting(ctx context.Context, blockID uuid.UUID) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetBlockFormatting", ctx, blockID)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetBlockFormatting indicates an expected call of ResetBlockFormatting.
func (mr *MockNoteRepositoryMockRecorder) ResetBlockFormatting(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetBlockFormatting", reflect.TypeOf((*MockNoteRepository)(nil).ResetBlockFormatting), ctx, blockID)
}

// ShiftBlockPositions mocks base method.
func (m *MockNoteRepository) ShiftBlockPositions(ctx context.Context, noteID uuid.UUID, fromPosition, direction int, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShiftBlockPositions", ctx, noteID, fromPosition, direction, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShiftBlockPositions indicates an expected call of ShiftBlockPositions.
func (mr *MockNoteRepositoryMockRecorder) ShiftBlockPositions(ctx, noteID, fromPosition, direction, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShiftBlockPositions", reflect.TypeOf((*MockNoteRepository)(nil).ShiftBlockPositions), ctx, noteID, fromPosition, direction, updatedAt)
}

// UpdateBlockContent mocks base method.
func (m *MockNoteRepository) UpdateBlockContent(ctx context.Context, blockID uuid.UUID, content string, updatedAt time.Time) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockContent", ctx, blockID, content, updatedAt)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockContent indicates an expected call of UpdateBlockContent.
func (mr *MockNoteRepositoryMockRecorder) UpdateBlockContent(ctx, blockID, content, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockContent", reflect.TypeOf((*MockNoteRepository)(nil).UpdateBlockContent), ctx, blockID, content, updatedAt)
}

// UpdateBlockFormatting mocks base method.
func (m *MockNoteRepository) UpdateBlockFormatting(ctx context.Context, blockID uuid.UUID, formattingRange models.FormattingRange) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockFormatting", ctx, blockID, formattingRange)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockFormatting indicates an expected call of UpdateBlockFormatting.
func (mr *MockNoteRepositoryMockRecorder) UpdateBlockFormatting(ctx, blockID, formattingRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockFormatting", reflect.TypeOf((*MockNoteRepository)(nil).UpdateBlockFormatting), ctx, blockID, formattingRange)
}

// UpdateNote mocks base method.
func (m *MockNoteRepository) UpdateNote(ctx context.Context, noteID uuid.UUID, note models.Note) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, noteID, note)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNoteRepositoryMockRecorder) UpdateNote(ctx, noteID, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNoteRepository)(nil).UpdateNote), ctx, noteID, note)
}
