// Code generated by MockGen. DO NOT EDIT.
// Source: notes.go
//
// Generated by this command:
//
//	mockgen -source=notes.go -destination=mocks/mock_handler_notes.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	bytes "bytes"
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_WHITECROWSOFT/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteUsecase is a mock of NoteUsecase interface.
type MockNoteUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockNoteUsecaseMockRecorder
	isgomock struct{}
}

// MockNoteUsecaseMockRecorder is the mock recorder for MockNoteUsecase.
type MockNoteUsecaseMockRecorder struct {
	mock *MockNoteUsecase
}

// NewMockNoteUsecase creates a new mock instance.
func NewMockNoteUsecase(ctrl *gomock.Controller) *MockNoteUsecase {
	mock := &MockNoteUsecase{ctrl: ctrl}
	mock.recorder = &MockNoteUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteUsecase) EXPECT() *MockNoteUsecaseMockRecorder {
	return m.recorder
}

// CreateBlock mocks base method.
func (m *MockNoteUsecase) CreateBlock(ctx context.Context, noteID, userID uuid.UUID, block models.Block) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlock", ctx, noteID, userID, block)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlock indicates an expected call of CreateBlock.
func (mr *MockNoteUsecaseMockRecorder) CreateBlock(ctx, noteID, userID, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlock", reflect.TypeOf((*MockNoteUsecase)(nil).CreateBlock), ctx, noteID, userID, block)
}

// CreateNote mocks base method.
func (m *MockNoteUsecase) CreateNote(ctx context.Context, note models.Note) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, note)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteUsecaseMockRecorder) CreateNote(ctx, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteUsecase)(nil).CreateNote), ctx, note)
}

// CreateSubnote mocks base method.
func (m *MockNoteUsecase) CreateSubnote(ctx context.Context, parentNoteID, userID uuid.UUID, note models.Note, hasPosition bool, position int) (*models.Note, uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubnote", ctx, parentNoteID, userID, note, hasPosition, position)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateSubnote indicates an expected call of CreateSubnote.
func (mr *MockNoteUsecaseMockRecorder) CreateSubnote(ctx, parentNoteID, userID, note, hasPosition, position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubnote", reflect.TypeOf((*MockNoteUsecase)(nil).CreateSubnote), ctx, parentNoteID, userID, note, hasPosition, position)
}

// DeleteBlock mocks base method.
func (m *MockNoteUsecase) DeleteBlock(ctx context.Context, blockID, noteID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, blockID, noteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockNoteUsecaseMockRecorder) DeleteBlock(ctx, blockID, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockNoteUsecase)(nil).DeleteBlock), ctx, blockID, noteID, userID)
}

// DeleteNote mocks base method.
func (m *MockNoteUsecase) DeleteNote(ctx context.Context, noteID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, noteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteUsecaseMockRecorder) DeleteNote(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNoteUsecase)(nil).DeleteNote), ctx, noteID, userID)
}

// DeleteSubnote mocks base method.
func (m *MockNoteUsecase) DeleteSubnote(ctx context.Context, noteID, subnoteID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubnote", ctx, noteID, subnoteID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubnote indicates an expected call of DeleteSubnote.
func (mr *MockNoteUsecaseMockRecorder) DeleteSubnote(ctx, noteID, subnoteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubnote", reflect.TypeOf((*MockNoteUsecase)(nil).DeleteSubnote), ctx, noteID, subnoteID, userID)
}

// GenerateNotePDF mocks base method.
func (m *MockNoteUsecase) GenerateNotePDF(ctx context.Context, noteID, userID uuid.UUID) (*bytes.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNotePDF", ctx, noteID, userID)
	ret0, _ := ret[0].(*bytes.Buffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateNotePDF indicates an expected call of GenerateNotePDF.
func (mr *MockNoteUsecaseMockRecorder) GenerateNotePDF(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNotePDF", reflect.TypeOf((*MockNoteUsecase)(nil).GenerateNotePDF), ctx, noteID, userID)
}

// GetNote mocks base method.
func (m *MockNoteUsecase) GetNote(ctx context.Context, noteID, userID uuid.UUID) (*models.Note, []models.Block, map[string]models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, noteID, userID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].([]models.Block)
	ret2, _ := ret[2].(map[string]models.BlockFormatting)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetNote indicates an expected call of GetNote.
func (mr *MockNoteUsecaseMockRecorder) GetNote(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockNoteUsecase)(nil).GetNote), ctx, noteID, userID)
}

// GetNotes mocks base method.
func (m *MockNoteUsecase) GetNotes(ctx context.Context, userID uuid.UUID) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotes", ctx, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotes indicates an expected call of GetNotes.
func (mr *MockNoteUsecaseMockRecorder) GetNotes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotes", reflect.TypeOf((*MockNoteUsecase)(nil).GetNotes), ctx, userID)
}

// GetPublicNote mocks base method.
func (m *MockNoteUsecase) GetPublicNote(ctx context.Context, noteID uuid.UUID) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicNote", ctx, noteID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicNote indicates an expected call of GetPublicNote.
func (mr *MockNoteUsecaseMockRecorder) GetPublicNote(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicNote", reflect.TypeOf((*MockNoteUsecase)(nil).GetPublicNote), ctx, noteID)
}

// GetSubnotes mocks base method.
func (m *MockNoteUsecase) GetSubnotes(ctx context.Context, noteID, userID uuid.UUID) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnotes", ctx, noteID, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnotes indicates an expected call of GetSubnotes.
func (mr *MockNoteUsecaseMockRecorder) GetSubnotes(ctx, noteID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnotes", reflect.TypeOf((*MockNoteUsecase)(nil).GetSubnotes), ctx, noteID, userID)
}

// MoveBlock mocks base method.
func (m *MockNoteUsecase) MoveBlock(ctx context.Context, blockID, noteID, userID uuid.UUID, newPosition int) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveBlock", ctx, blockID, noteID, userID, newPosition)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveBlock indicates an expected call of MoveBlock.
func (mr *MockNoteUsecaseMockRecorder) MoveBlock(ctx, blockID, noteID, userID, newPosition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveBlock", reflect.TypeOf((*MockNoteUsecase)(nil).MoveBlock), ctx, blockID, noteID, userID, newPosition)
}

// ShiftBlockPositions mocks base method.
func (m *MockNoteUsecase) ShiftBlockPositions(ctx context.Context, noteID uuid.UUID, fromPosition, direction int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShiftBlockPositions", ctx, noteID, fromPosition, direction)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShiftBlockPositions indicates an expected call of ShiftBlockPositions.
func (mr *MockNoteUsecaseMockRecorder) ShiftBlockPositions(ctx, noteID, fromPosition, direction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShiftBlockPositions", reflect.TypeOf((*MockNoteUsecase)(nil).ShiftBlockPositions), ctx, noteID, fromPosition, direction)
}

// UpdateBlockContent mocks base method.
func (m *MockNoteUsecase) UpdateBlockContent(ctx context.Context, blockID, noteID, userID uuid.UUID, content string) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockContent", ctx, blockID, noteID, userID, content)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockContent indicates an expected call of UpdateBlockContent.
func (mr *MockNoteUsecaseMockRecorder) UpdateBlockContent(ctx, blockID, noteID, userID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockContent", reflect.TypeOf((*MockNoteUsecase)(nil).UpdateBlockContent), ctx, blockID, noteID, userID, content)
}

// UpdateBlockFormatting mocks base method.
func (m *MockNoteUsecase) UpdateBlockFormatting(ctx context.Context, blockID, noteID, userID uuid.UUID, formattingRange models.FormattingRange) (*models.BlockFormatting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockFormatting", ctx, blockID, noteID, userID, formattingRange)
	ret0, _ := ret[0].(*models.BlockFormatting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockFormatting indicates an expected call of UpdateBlockFormatting.
func (mr *MockNoteUsecaseMockRecorder) UpdateBlockFormatting(ctx, blockID, noteID, userID, formattingRange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockFormatting", reflect.TypeOf((*MockNoteUsecase)(nil).UpdateBlockFormatting), ctx, blockID, noteID, userID, formattingRange)
}

// UpdateNote mocks base method.
func (m *MockNoteUsecase) UpdateNote(ctx context.Context, noteID, userID uuid.UUID, note models.Note) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, noteID, userID, note)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNoteUsecaseMockRecorder) UpdateNote(ctx, noteID, userID, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNoteUsecase)(nil).UpdateNote), ctx, noteID, userID, note)
}
